---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/groups":
    get:
      summary: list groups
      responses:
        '200':
          description: successful
    post:
      summary: create group
      responses:
        '200':
          description: successful
  "/api/v1/groups/new":
    get:
      summary: new group
      responses:
        '200':
          description: successful
  "/api/v1/groups/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit group
      responses:
        '200':
          description: successful
  "/api/v1/groups/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show group
      responses:
        '200':
          description: successful
    patch:
      summary: update group
      responses:
        '200':
          description: successful
    put:
      summary: update group
      responses:
        '200':
          description: successful
    delete:
      summary: delete group
      responses:
        '200':
          description: successful
  "/api/v1/inventories":
    get:
      summary: list inventories
      responses:
        '200':
          description: successful
    post:
      summary: create inventory
      responses:
        '200':
          description: successful
  "/api/v1/inventories/new":
    get:
      summary: new inventory
      responses:
        '200':
          description: successful
  "/api/v1/inventories/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit inventory
      responses:
        '200':
          description: successful
  "/api/v1/inventories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show inventory
      responses:
        '200':
          description: successful
    patch:
      summary: update inventory
      responses:
        '200':
          description: successful
    put:
      summary: update inventory
      responses:
        '200':
          description: successful
    delete:
      summary: delete inventory
      responses:
        '200':
          description: successful
  "/api/v1/warehouses":
    get:
      summary: list warehouses
      responses:
        '200':
          description: successful
    post:
      summary: create warehouse
      responses:
        '200':
          description: successful
  "/api/v1/warehouses/new":
    get:
      summary: new warehouse
      responses:
        '200':
          description: successful
  "/api/v1/warehouses/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit warehouse
      responses:
        '200':
          description: successful
  "/api/v1/warehouses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show warehouse
      responses:
        '200':
          description: successful
    patch:
      summary: update warehouse
      responses:
        '200':
          description: successful
    put:
      summary: update warehouse
      responses:
        '200':
          description: successful
    delete:
      summary: delete warehouse
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
